CREATE TABLE IF NOT EXISTS Genre (
	id SERIAL PRIMARY KEY,	
	name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Musician (
	id SERIAL PRIMARY KEY,	
	name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Albom (
	id SERIAL PRIMARY KEY,	
	name VARCHAR(40) NOT NULL,
	year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Track (
	id SERIAL PRIMARY KEY,	
	name VARCHAR(40) NOT NULL,
	duration INTEGER NOT NULL,
	albom_id INTEGER NOT NULL REFERENCES Albom(id)
);

CREATE TABLE IF NOT EXISTS Compilation (
	id SERIAL PRIMARY KEY,	
	name VARCHAR(40) NOT NULL,
	year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Genre_Mucisian (
	genre_id INTEGER REFERENCES Genre(id),
	musician_id INTEGER REFERENCES Musician(id),
	CONSTRAINT pk PRIMARY KEY (genre_id, musician_id)
);

CREATE TABLE IF NOT EXISTS Compilation_Track (
	id SERIAL PRIMARY KEY,
	compilation_id INTEGER NOT NULL REFERENCES Compilation(id),
	track_id INTEGER NOT NULL REFERENCES Track(id)	
);

CREATE TABLE IF NOT EXISTS Musician_Albom (
	id SERIAL PRIMARY KEY,
	musician_id INTEGER NOT NULL REFERENCES Musician(id),
	albom_id INTEGER NOT NULL REFERENCES Albom(id)	
);